#!/usr/bin/bash
scriptDir="$(dirname "$0")"
(cd $scriptDir && make compile)
if [ "$1" == "" ]; then
help=$'Please use the following commands:
LSB encode:        audioSteg -le raw.wav input.file encoded.wav
LSB decode:        audioSteg -ld encoded.wav output.file
freq encode:       audioSteg -fe raw.wav input.file encoded.wav frequency
freq decode:       audioSteg -fd encoded.wav output.file frequency
file diff:         audioSteg -df one.wav two.wav output.file
bit resample:      audioSteg -br 16bit.wav 32bit.wav resampleRate
write 3rd channel: audioSteg -ce raw.wav
read 3rd channel:  audioSteg -cd encoded.wav'
echo "$help"
fi
if [ "$1" == "-le" ]; then
$scriptDir/program encode $2 $3 $4
fi
if [ "$1" == "-ld" ]; then
$scriptDir/program decode $2 $3
fi
if [ "$1" == "-fe" ]; then
$scriptDir/program freqEncode $2 $3 $4 $5
fi
if [ "$1" == "-fd" ]; then
$scriptDir/program freqDecode $2 $3 $4
fi
if [ "$1" == "-df" ]; then
$scriptDir/program diff $2 $3 $4
fi
if [ "$1" == "-br" ]; then
$scriptDir/program bitResample $2 $3 $4
fi
if [ "$1" == "-ce" ]; then
$scriptDir/program channelWrite $2 $3 $4 $5
fi
if [ "$1" == "-cd" ]; then
$scriptDir/program channelRead $2 $3
fi
